//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public CustomerOrder()
        {
            this.CustomerOrderLines = new HashSet<CustomerOrderLine>();
        }
    
        public int customerOrderID { get; set; }
        public int customerOrderStateID { get; set; }
        public int customerID { get; set; }
        public int customerOrderPaymentMethodID { get; set; }
        public System.DateTime customerOrderDate { get; set; }
        public Nullable<decimal> customerOrderAdvancePayment { get; set; }
    
        public virtual ICollection<CustomerOrderLine> CustomerOrderLines { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OrderState CustomerOrderState { get; set; }
        public virtual CustomerOrderPaymentMethod CustomerOrderPaymentMethod { get; set; }
    }
}
