//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderPaymentMethod
    {
        public CustomerOrderPaymentMethod()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int customerOrderPaymentMethodID { get; set; }
        public string customerOrderPaymentMethodName { get; set; }
        public string customerOrderPaymentMethodDescription { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
