//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int customerID { get; set; }
        public int customerRoleID { get; set; }
        public string customerForename { get; set; }
        public string customerSurname { get; set; }
        public string customerPhone { get; set; }
        public string customerEmail { get; set; }
        public string customerUsername { get; set; }
        public string customerPassword { get; set; }
        public string customerAddressHouseNo { get; set; }
        public string customerAddressStreet1 { get; set; }
        public string customerAddressStreet2 { get; set; }
        public string customerAddressTown { get; set; }
        public string customerAddressCounty { get; set; }
        public string customerAddressPostCode { get; set; }
        public string customerAddressCountry { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual Role CustomerRole { get; set; }
    }
}
