//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderState
    {
        public OrderState()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.SupplierOrders = new HashSet<SupplierOrder>();
        }
    
        public int orderStateID { get; set; }
        public string orderStateName { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual ICollection<SupplierOrder> SupplierOrders { get; set; }
    }
}
