//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductApproval
    {
        public ProductApproval()
        {
            this.productApprovalID = 1;
            this.Products = new HashSet<Product>();
        }
    
        public int productApprovalID { get; set; }
        public string productApprovalName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
