//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.productApprovalID = 1;
            this.productWHSPrice = 0m;
            this.productSNWPrice = 0m;
            this.CustomerOrderLines = new HashSet<CustomerOrderLine>();
        }
    
        public int productID { get; set; }
        public int productCategoryID { get; set; }
        public int productApprovalID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string productOrganicStatus { get; set; }
        public string productOrigin { get; set; }
        public decimal productWHSQty { get; set; }
        public string productWHSsize { get; set; }
        public decimal productWHSPrice { get; set; }
        public short productSNWDivisor { get; set; }
        public decimal productSNWPrice { get; set; }
        public System.DateTime productDateLastChanged { get; set; }
        public System.DateTime productPriceLastChanged { get; set; }
    
        public virtual ICollection<CustomerOrderLine> CustomerOrderLines { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductApproval ProductApproval { get; set; }
    }
}
