//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int roleID { get; set; }
        public string roleName { get; set; }
        public string roleDescription { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
