//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        public SupplierOrder()
        {
            this.CustomerOrderLines = new HashSet<CustomerOrderLine>();
        }
    
        public int supplierOrderID { get; set; }
        public int supplierOrderStateID { get; set; }
        public int supplierID { get; set; }
        public Nullable<System.DateTime> supplierOrderDeadline { get; set; }
        public System.DateTime supplierOrderDate { get; set; }
        public Nullable<System.DateTime> supplierOrderReqDeliveryDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual ICollection<CustomerOrderLine> CustomerOrderLines { get; set; }
    }
}
