//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierOrders = new HashSet<SupplierOrder>();
        }
    
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string supplierPhone { get; set; }
        public string supplierEmail { get; set; }
        public string supplierAddressHouseNo { get; set; }
        public string supplierAddressStreet1 { get; set; }
        public string supplierAddressStreet2 { get; set; }
        public string supplierAddressTown { get; set; }
        public string supplierAddressCounty { get; set; }
        public string supplierAddressPostCode { get; set; }
        public string supplierAddressCountry { get; set; }
    
        public virtual ICollection<SupplierOrder> SupplierOrders { get; set; }
    }
}
